plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.6.1'
}

version = project.hasProperty('release') ? project.getProperty('release') : '1.0'

repositories {
    mavenCentral()
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
    maven { url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/' }
    mavenLocal()
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.1.2.build.74-stable'
    compileOnly 'org.jetbrains:annotations:24.1.0'
    implementation "net.kyori:adventure-api:4.17.0"
    implementation "net.kyori:adventure-platform-bukkit:4.3.4"
}

processResources {
    inputs.property "version", project.version

    filesMatching("plugin.yml") {
        expand "version": project.version
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

jar {
    archiveClassifier.set('unshaded')
    enabled = false
}

shadowJar {
    archiveClassifier.set('')
    archiveFileName = "motd-enhanced-${project.version}.jar"
}

tasks.assemble.dependsOn tasks.shadowJar
tasks.jar.finalizedBy tasks.shadowJar
